### ISSUE TITLE
Support the same versions ProtocolSupport supports

### ISSUE THREAD

**Issue by ant-7802** [ViaVersion/ViaProxy#142]
It would be nice to allow 1.4, 1.5, and 1.6 users to join my Minecraft server. Will support for these versions ever be added?

**Comment by Gaming32** [comment]
It would be a pretty useless feature compared to the insane amount of work it would take to implement.

**Comment by RaphiMC** [comment]
ProtocolSupport can't be implemented on a proxy because it relies on server data access. And coding those protocol translations from scratch would be a lot of work which its not really worth it for the couple of minutes someone would use those versions (Due to how unplayable and buggy it would be because almost all blocks and items are missing). 1.7 is already only barely playable because of through how many protocol translation layers it has to go
