### ISSUE TITLE
Online Mode Proxying does not appear to function

### ISSUE THREAD

**Issue by hibiii** [ViaVersion/ViaProxy#157]
I am a player trying to connect to a 20.4 server from a 20.1 client. I am a new user, but I have been looking at public documentation and I cannot find any.

Using the GUI, the tooltip on the Proxy Online Mode tickbox implies that the responsibility of auth is delegated to the connecting client because it "requires your client to have a valid minecraft account", and my client does as I can login to 20.1 compatible online servers, unproxied, with no problem.

However, when I use ViaProxy (both with GUI and with CLI args, `-o` included), I am unable to connect to the proxied server, and ViaProxy itself prevents me from joining with the message: `[PROXY KICK] (127.0.0.1 | hibiscvs) This server is in online mode and requires a valid authentication mode.`

Settings I've tried (GUI):
- No online mode proxy, and "use selected account" with none registered, following the usage in the readme (default settings),
- No online mode proxy, but "use no account",
- Online mode proxy with "use selected account" with none registered,
- Online mode proxy with "use no account".

Version: GitHub Release 3.0.23 non-Java-8: `git-ViaProxy-3.0.23:9cf8708`

**Comment by RaphiMC** [comment]
Did you ever add an account in the accounts tab? ViaProxy only works if you add an account there since a proxy application can't ever join other online mode servers without having access to the account tokens. The Proxy Online Mode option is there to have chat signing and skin support (It says that in the tooltip as well). By enabling that you need a valid minecraft account on your client since ViaProxy will act like a server in online mode

**Comment by hibiii** [comment]
I have just now, but it does not use the account I have selected on my Minecraft client, the sole reason I was reluctant to use it in the first place. I'd rather use the methods I already use for account switching than to restart the proxy every time I want to switch accounts, because otherwise I feel it'll inevitably lead to me mismanaging the accounts, thinking the Minecraft client is logged in with the account that the proxy is logged in with.

Additionally, how is it done for public proxies for public online mode servers? Asking because I feel this would be the closest usecase to my preferred setup.

**Comment by RaphiMC** [comment]
Public proxies for public online mode servers aren't really something thats possible without modifying the client (by installing a mod) or by adding a lot of complexity to the setup (Use VIAaaS if you want that). If your client version is <= 1.19.4 you can install OpenAuthMod on your clients and use that in ViaProxy, this will also mean that accounts are managed on the client again instead of the proxy

**Comment by hibiii** [comment]
Thanks for answering, by the way. Closing because I realize that this is a bit of a skill issue on my part for not reading enough.
