### ISSUE TITLE
ViaProxy 3.2.1 Incompatibility with Realms

### ISSUE THREAD

**Issue by jane0009** [ViaVersion/ViaProxy#208]
Hi! I am using the latest release (3.2.1), and attempting to use it to connect to a realm. I am able to properly log in with a Microsoft account, and select that account, but when i switch to the Realms tab I get the message:
"Your ViaProxy is outdated and not compatible with Minecraft Realms.Please use the latest version of ViaProxy."

On a slightly unrelated note, this message gets cut off when the window is set to its default size:
![Screenshot 2024-04-26 171547](https://github.com/ViaVersion/ViaProxy/assets/8826006/589c6f0a-f1bf-4a0f-a95b-7aa766fdf36f)

Also, I am running the jar through the console (just using `java -jar ViaProxy-3.2.1.jar`) and there are no errors there. I am running Java 21, if that changes anything.

**Comment by RaphiMC** [comment]
Thanks for reporting this issue. The problem with this is, that Mojang already announced that 1.20.6 will be coming out early next week and thus ViaProxy already supports 1.20.6. When sending requests for Realms it uses the latest supported version (Which happens to be 1.20.6 in this case). But because 1.20.6 is not yet released the Realms API says that the version is unsupported.
I won't make a new release of ViaProxy because 1.20.6 will come out in less than a week (Which would fix this issue). I made a ViaProxy build with the version set to 1.20.5: https://upload.raphimc.net/file/3xgccHXRUKXQtN7K/JnhRZ9gnv1HG9KAb/ViaProxy-3.2.2-SNAPSHOT.jar
You can use this until 1.20.6 is officially released. I will also leave this issue open until 1.20.6 is released, so anyone else having this problem can quickly find the workaround

**Comment by jane0009** [comment]
cheers, thanks!

**Comment by RaphiMC** [comment]
1.20.6 is released and the normal release version of ViaProxy should work again with Realms
