### ISSUE TITLE
Update Supported

### ISSUE THREAD

**Issue by lZiMUl** [ViaVersion/ViaProxy#210]
When will Minecraft Bedrock Edition 1.20.80 be supported

**Comment by FlorianMichael** [comment]
There is no ETA on when updates are getting finished, afaik RaphiMC is working on the ViaBedrock update and it _should_ be ready in a few days.

**Comment by lZiMUl** [comment]
Okay

**Comment by lZiMUl** [comment]
Support you guys😁

**Comment by RaphiMC** [comment]
The main update is already done, but due to the large amount of technical changes its not fully done yet and thus I haven't updated ViaBedrock in ViaProxy yet. There is early testing going on on my discord (https://discord.gg/dCzT9XHEWu) and the update will release in a couple of days if there are no major issues discovered in testing
