### ISSUE TITLE
All kinds of errors / crashes when using ViaProxy

### ISSUE THREAD

**Issue by bramcia** [ViaVersion/ViaProxy#231]
I receive a lot of different kick messages when using the Proxy / Fabric and even ViaForge.

- Buffer Underflow
- Premature end of stream (expected .... bytes, got ... bytes)
- Packet 0/25 (gz) was larger than I expected, found 124 bytes extra whilst reading packet 25
- Connection terminated

Need help fixing this issue. I play on Lunar, Laby, Forge and Fabric.
Have tried reinstalling, adding memory, closing all apps, using no VPN.......

**Comment by RaphiMC** [comment]
Your issue should only contain one error at a time. Please upload a ViaProxy log for each one and provide additional details like the used client (and mod list)

**Comment by bramcia** [comment]
Sorry man I just wrote them all down with using Crashes as main issue..
Mods: 
- Optifine + Optiforge, or no mods.
I play on clients: Lunar, Laby, or just the MC Launcher with: Forge and Fabric.
[latest.log](https://github.com/user-attachments/files/15873428/latest.log) LOGS, just played.

I want to add these crashes occur on Cubecraft mostly. I tried it on MCCisland and did **not** receive crashes.

**Comment by RaphiMC** [comment]
There are no relevant errors in the ViaProxy log, so it seems that Cubecraft probably sends broken packets or their anticheat detects one of the wrong packets from ViaVersion resulting in a disconnect. I will close the issue because ViaProxy (ViaVersion strictly speaking) is not made to play on servers with strict anticheats (Cubecraft) and the issue is not reproduceable outside of that server (I am not interested in getting my account banned by testing on their server).
