### ISSUE TITLE
Bedrock Support

### ISSUE THREAD

**Issue by spactoking** [ViaVersion/ViaProxy#317]
Is it possible to connect to the proxy server from bedrock to a bedrock server but just different version
for example: client: bedrock 1.20 , server : bedrock 1.21.40 using the proxy.
If not can that be implemented as it would make the java to bedrock translation work gone and wud be easier or if its not gonna be implemented , how can i edit the code for it to do so on a private proxy

**Comment by RaphiMC** [comment]
ViaProxy has no bedrock client support by default, so you would need to add the Geyser plugin to it. Geyser should support 1.20.0. Then you can use ViaProxy to join Bedrock 1.20.40 servers. But because this is going through the Java Edition protocol it will be very unplayable, because ViaBedrock (Java client -> Bedrock server protocol translation) isn't finished yet.

**Comment by spactoking** [comment]
wouldn't it be easier to add bedrock client support with just the version translation instead of java client to bedrock server
