### ISSUE TITLE
How to keep player online after disconnecting from proxy server

### ISSUE THREAD

**Issue by tranarchy** [ViaVersion/ViaProxy#329]
I would like to make it so after the client disconnects from the proxy server the player remains online on the real server.

What I tried so far is getting rid of `public void channelInactive`, which did keep the player online after disconnecting from the proxy, however the channel still closed, it no longer received packets and the real server eventually kicks the player due to a timeout. However thats not the only issue since even if I log back in before the timeout, the server handles this as a new login. I tried messing with the `DisconnectPacketHandler` as well but had the same outcome.

I know this is probably not the right place to ask about this but if anyone could give me directions about what should I do to achieve this I would really appreciate it!

**Comment by RaphiMC** [comment]
This isn't easily possible with ViaProxy (Because its not designed to handle all minecraft packets like a vanilla client), but you can check this project out which should be able to do what you want: https://github.com/rfresh2/ZenithProxy

**Comment by tranarchy** [comment]
Thanks!

**Comment by tranarchy** [comment]
I would still like to see what I could do though. The timeout part is not really an issue, I would only disconnect from the server for a few seconds before logging back in, the main problem is the proxy sending a new login to the real server every time I join back after disconnecting. Do you think I could solve that somehow?

**Comment by RaphiMC** [comment]
Reusing the connection is the smaller problem (You can just store the ProxyConnection instance somewhere and reuse that when the client reconnects instead of creating a new ProxyConnection). The largest would be that you would have to resend the whole world and all entities and data because the server won't send the world twice because it thinks the client still has it loaded. This means you will have to implement and handle most minecraft packets (Which is a huge amount of work)
