### ISSUE TITLE
[Question] Passing through real IP addresses during handshake

### ISSUE THREAD

**Issue by LOOHP** [ViaVersion/ViaProxy#334]
I would like to know whether there are any simple ways to set ViaProxy up so that I can passthrough the real IP addresses of players during the **handshake phase**, possibly with a ViaProxy plugin.

Perhaps an event that would like me inject something into the address field of the handshake packet?

Thank you in advance!

**Comment by RaphiMC** [comment]
There is a simple way which is aleady integrated in ViaProxy for that exact purpose. You can enable `backend-haproxy` in the ViaProxy config. You also need to enable HAProxy support on the target server (Or add HAProxy support). Alternatively I can add an event to modify the handshake packet, although I strongly recommend using HAProxy, because thats the standard protocol almost every server/proxy supports nowadays (Bungeecord, Spigot, Geyser, ...)

**Comment by LOOHP** [comment]
My custom server implementation in the backend doesn't use Netty. Having to implement HAProxy seems quite the hurdle. Perhaps modifying the handshake packet would be easier.

**Comment by RaphiMC** [comment]
I am deciding against providing an event because I can't think of a way to have proper API which works when multiple plugins (or the internal bungeecord player info forwarding) modify the handshake address. Instead you can modify the raw address when the packet is sent to the server and handle potential conflicts in your code. To do that you can add a netty handler to the server pipeline. Here is example code:

```java
static {
    ViaProxy.EVENT_MANAGER.register(yourclass.class);
}

@EventHandler
private static void onProxy2ServerChannelInitialize(final Proxy2ServerChannelInitializeEvent event) {
    if (event.getType() != ITyped.Type.POST || event.isLegacyPassthrough()) {
        return;
    }

    event.getChannel().pipeline().addLast(new ChannelOutboundHandlerAdapter() {
        @Override
        public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
            if (msg instanceof C2SHandshakingClientIntentionPacket packet) {
                System.out.println("handshake address: " + packet.address);
                // packet.address = "...";
            }
            super.write(ctx, msg, promise);
        }
    });
}
```

**Comment by LOOHP** [comment]
Thank you for the example! I ended up sending the read address as an optional string directly through the pipeline before the handshake packet and have my server implementation read that before anything. It is working great!
