### ISSUE TITLE
clientHandshakeAddress is unused when constructing ClientIntention packet

### ISSUE THREAD

**Issue by mat-1** [ViaVersion/ViaProxy#338]
Setting the `wildcard-domain-handling` to `INTERNAL` and connecting to `asdf\x07localhost:25566\x071.20.4` results in the client connecting to `127.0.0.1:25566` and sending the hostname in the intention packet as `localhost`. The expected behavior is that it would send `asdf` as the hostname instead.

This seems to be because the `clientHandshakeAddress` variable that's set to the first argument you passed, is never used when constructing the ClientIntention packet to send: https://github.com/ViaVersion/ViaProxy/blob/1757724fa7373abaccdba243ae281febc6b3f8a7/src/main/java/net/raphimc/viaproxy/proxy/client2proxy/Client2ProxyHandler.java#L269-L275

The correct code here would be something like
```java
final String address = clientHandshakeAddress.getHost();
final int port = clientHandshakeAddress.getPort();
```
(I tested it, it does work as expected).

Though, `clientHandshakeAddress` can be null if it's invalid, so I guess it should show an error or use the old code as a fallback or something in that case.

**Comment by RaphiMC** [comment]
ViaProxy never sends the original handshake address to the server, as that would be the wrong behaviour and easily blockable by servers (And some, especially Anti-DDoS provider even do that already). Instead it replaces it with the configured target address which results in it sending the same data to the server as a vanilla client connecting directly to the server.

The point of passing the original handshake address (`asdf` in your example) is purely for ViaProxy internal handling. An example of its usage is the transfer packet handler. The transfer packet handler rewrites the target address of incoming transfer packets to the client handshake address, so the client reconnects to ViaProxy instead of connecting to the target server directly.

**Comment by mat-1** [comment]
Oh, I see...

I will note that it would be a little useful to be able to modify the connection address independently from the address sent in the intention packet, as it's possible for servers to have special behavior for addresses that aren't resolvable. But to be fair, I can't think of any real servers that do this that wouldn't already be covered by the existing splitting by \0. It's not a massive deal, I appreciate your response. <3
